services:
  main_api:
    build:
      context: .
      dockerfile: bin/main_api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/src:ro
      - ~/.aws/credentials:/root/.aws/credentials:ro

  chat_api:
    build:
      context: .
      dockerfile: bin/chat_api/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/src:ro
      - ~/.aws/credentials:/root/.aws/credentials:ro
  
  dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   user: root
   volumes:
     - dynamodb-data:/home/dynamodblocal/data
   working_dir: /home/dynamodblocal

  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/15/bin
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
  dynamodb-data:
